name: quan_ly_xuong
description: "A Flutter project for managing a wood workshop."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ==================== HỖ TRỢ CHUNG ====================
  flutter_easyloading: ^3.0.5
  photo_view: ^0.15.0
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  path: ^1.8.3
  mime: ^1.0.4
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  convert: ^3.1.1
  http: ^1.2.0                            # Giữ lại bản mới nhất

  # ==================== FIREBASE ====================
  firebase_core: ^3.6.0

  # ==================== MẠNG & DỮ LIỆU ====================
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2

  # ==================== MỞ LINK, GỌI ĐIỆN, URL ====================
  url_launcher: ^6.3.0

  # ==================== BIỂU ĐỒ & ĐỒ HỌA ====================
  fl_chart: ^0.68.0

  # ==================== QR / BARCODE ====================
  mobile_scanner: ^3.5.7              # Quét mã QR / barcode bằng camera
  qr_flutter: ^4.1.0                  # Tạo mã QR (QrPainter)
  barcode: ^2.2.6                     # Tạo mã vạch
  barcode_widget: ^2.0.3              # Hiển thị barcode
  qr_code_tools: ^0.2.0               # Đọc QR từ ảnh
  google_mlkit_barcode_scanning: ^0.11.0 # Quét QR từ ảnh MLKit
  permission_handler: ^11.3.0         # Quyền truy cập file/ảnh

  # ==================== IN ẤN / XUẤT FILE ====================
  pdf: ^3.10.7                        # Tạo file PDF
  printing: ^5.12.0                   # In và chia sẻ PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # ==================== MOCK & CÔNG CỤ PHÁT TRIỂN ====================
  firebase_auth_mocks: ^0.14.2
  google_sign_in_mocks: ^0.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/fonts/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/DejaVuSans.ttf
    - assets/fonts/DejaVuSans-Bold.ttf

# ==================== CẤU HÌNH ICON APP ====================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# ==================== CẤU HÌNH SPLASH SCREEN ====================
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: true
  web: true
