name: quan_ly_xuong
description: "A Flutter project for managing a wood workshop."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.4
  path: ^1.8.3
  mime: ^1.0.4
  intl: ^0.18.1
  fl_chart: ^0.68.0   # ✅ vẽ biểu đồ
  shared_preferences: ^2.0.15
  mobile_scanner: ^3.0.0
  qr_flutter: ^4.0.0   # (tuỳ chọn) nếu bạn muốn hiện QR cho laptop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
