name: quan_ly_xuong
description: "A Flutter project for managing a wood workshop."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Hiển thị loading, ảnh, chia sẻ, đường dẫn, ...
  flutter_easyloading: ^3.0.5
  photo_view: ^0.15.0
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  path: ^1.8.3
  mime: ^1.0.4
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  convert: ^3.1.1

  # Firebase
  firebase_core: ^3.6.0

  # Gửi link, mở URL
  url_launcher: ^6.3.0

  # Gọi API, lưu trữ, chọn ảnh
  http: ^0.13.6
  image_picker: ^1.0.4
  shared_preferences: ^2.0.15

  # Biểu đồ & đồ họa
  fl_chart: ^0.68.0

  # Quét mã QR / mã vạch
  mobile_scanner: ^3.5.7        # ✅ bản mới nhất (bỏ allowDuplicates)
  qr_flutter: ^4.1.0            # ✅ tạo QR code
  barcode: ^2.2.6               # ✅ tạo barcode cơ bản
  barcode_widget: ^2.0.3        # ✅ tạo BarcodeWidget (giải lỗi của bạn)

  # Xuất PDF / In ấn
  pdf: ^3.10.7
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_auth_mocks: ^0.14.2
  google_sign_in_mocks: ^0.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/icon/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf

# ✅ Cấu hình icon app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# ✅ Cấu hình splash screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: true
  web: true
